repos:
  - repo: local
    hooks:
      - id: ruff check
        name: ruff check
        entry: ruff check --select I . --fix
        language: system
        types: [python]
      - id: ruff format
        name: ruff format
        entry: ruff format .
        language: system
        types: [python]
