BGG_API_V1_BASE_URL = "http://boardgamegeek.com/xmlapi"

FONT_TITLE = 24
FONT_LARGE = 20
FONT_MEDIUM = 18
FONT_SMALL = 14
COMPONENT_PADDING = 16
COMPONENT_SPACING = 10
COMPONENT_RADIUS = 10
CARD_WIDTH = 250
CARD_HEIGHT = 250
GRID_COLUMNS = 4
SNACKBAR_DURATION_MS = 3000
